---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./homeassistant.yaml
  - ./truenas.yaml
  - ./udm.yaml
#  - ./notifiarr.yaml
#  - ./calibre-web.yaml
