ansible_become_pass: ENC[AES256_GCM,data:A2KDIFuPgL5qyWGHQneeUIy/,iv:JtFfV5bWPOJDyvVbiuW3lkFkXEwWB4ReX90jqkjhoGY=,tag:YqGScNGIP6s2RtW7n2DYhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10evyvm8h8ez8wwftltzy6ccg4kk3q3r5rfgkv3e7d83l298a5ufsgmv6er
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYjVtMjFSNGMxUVhUN1Iz
            d0llQkNHUkxCd2xYbWZ3ZzdiNE55MmZJM1JrClFka2FscXpCYzJtcisybkxEQjRk
            YlN2Q0UwWC8wMm0zYkFWRVF3NDBDV0EKLS0tIE1jUnlMVXRGdFJobXlkckpTVzRZ
            eC81NWpPZ2lIM1p0L2dxZDhRTWxUeHMK78fIGnz95mZuBr/84Jwp7BTOQmHc0Xs/
            R5meXHvVptCP+7a2JQNqIwClSE8rEm4Z2C8vfnziPXP/hk+1lIVQxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T20:27:45Z"
    mac: ENC[AES256_GCM,data:ZlIXT+WyktTTsYYkyyqZPQx+djtmIAKXx/yypngrGjTEzT9hTGrVQ6YVURgme7ZN9V882QmDHWuuLzaJqAkKax0fhKtkk+is1zRp9UA4vwycJabe8KiB+NBzGA7OzJItW+p1FF+y9OFx8zakn9Ax1zhyBXFNCUqU3yx7Mb+rXkc=,iv:tV37EfmJUwfJCsZit5lvVaxbbZL+f4RuBdtfCiDL38I=,tag:k87s0hc85mUKg/kBWyZKWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
