---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./hajimari/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./sonarr/ks.yaml
  - /radarr/ks.yaml
