apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:QQy2b2MoNIcK2GhReyPFJpHw7OnICZyiTEIF1e8BiE/Z5TbZ2HLYVyGHt7JRNUv4n1TBJlUG9H1zj9Az,iv:I+eDImxTpW7T7tOSfs89+qsITcNx6IScdgMiRcYnQfY=,tag:tZYqMP18PiQfW/BlftlYIQ==,type:str]
    username: ENC[AES256_GCM,data:FD6uBg0=,iv:MR9C8xEPu0pwVTSgMv1bMlCXtzERVykWOCAh4YBTewg=,tag:zTxLvTZl7zAOctBBNRfFHw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10evyvm8h8ez8wwftltzy6ccg4kk3q3r5rfgkv3e7d83l298a5ufsgmv6er
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MUZvSmt0YjJTY0tDalNF
            NlpJVE5Fd04xODZkM2prOExNYk9QK2RVWkMwCnB6anIrWE4vMHk5LzNlTStrZTRH
            cm9KU2xHbFQxL1BCMUdCcmxOQStQelkKLS0tIFAyeWxUSTFGalRDVlpJaW9Uc2JI
            b2RjVzZ3ZDlEWXRBLzJkdVppaXNQN28KFfBc/vH5Z0ISiQ6aDOKrftWjYMLE0hIH
            /y11B8QRlr/xM5OXE9T90IUNftnv/bfXaeQGnI76J22PAd93Wh0Kmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T10:03:37Z"
    mac: ENC[AES256_GCM,data:zcMaLhvZVfP0AV565EBnl5oFNnuHelt9YbUTc5Qrnd3zjqC55zatd9aWsjLw6BInoRJks7X+u9v3F6nVdGoK8SvEctibdC5SzNr0rXKmey97UDVPwD2a+Ek3bg2khc91YfKE9wG9Aee6q2VeDHprZUOd0tktCK8ZGjGQROqM1PA=,iv:ODBa24wXoXlbbLUy0AFAh2Gsc8Ryjwl5r8gODyD8rwc=,tag:HgjPpa5nBFRiJEC8bCl+IQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
