apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:P52tBLmsMR+Cl5iZ,iv:O82Y8n4Gy9deP1yVV3Nl07tlpBTCUkE++jlGd2E8Tp4=,tag:4tLrTOafv7UfVaAl0PbyFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10evyvm8h8ez8wwftltzy6ccg4kk3q3r5rfgkv3e7d83l298a5ufsgmv6er
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNkc2SFRZbGl6SHJPRU9l
            VlQybTl0bkNTYVpSZUlJV2hJRFpWMjVrZWtVCnN6a3dYMERLWVlPTi9ZaThPWEFV
            NHowQTRRZmlTOWRhY2ZmenRrQnVweU0KLS0tIDJCY2xwMVh6d1pNR1MrYTY2WW02
            dkJUdzYrcW4rM04reFRZZXl3bDk5L0UKabsw3w+oex+ya2hWQhtxMOLxoffbCiSi
            cGTxZ2DW8iuSC0thmqhRHPAI9KkxYTV5J5M8uFvZIjl4NdWBdhRkiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T10:03:06Z"
    mac: ENC[AES256_GCM,data:zut1A775FZVnQ3SsJBnoGNc+GlOODJqc9oBU7KJm4rC3YB5+qk1hGMuB6h8my+xt9EbUE7pkZJfkUGpC2IU6q0BL5x1EiSpTPHxgrctMq/8v0BVycwi2MfwDW7ZbaXHng/8djdIHDrqQGDOXxpY0IB3mbYfgD+VF4bh8Pi98Vyo=,iv:YO4g4hGKgShvJsBsUhopwIy934HCt2A9Mp9ob5ir2zU=,tag:blJc6bfX41lZe9C1W7HpaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
