apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:vwsDaPdFsIGNVnuLFonyd3q48N8=,iv:L8S0D7avoOrpWB5n54RNH3xBBv8kfO6xqkQ0DtscpoQ=,tag:ZTQAaMwYbBkg7xOJaohIQQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:OqdKePZnrnEkQUkFzZ0yj1t668mHheWJ+SIH4ps6wdGk0zfo,iv:fthJDw7rHOUHZ5bARHze2gpMLts3cEma5GnUntTag58=,tag:Ih6z1LSxQDntCjzb0a+QKw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:NbbslnTjYox+,iv:H19vqYiWmNwuO7OGrJD4mUl36nZXUl9/mpCw60z7Alc=,tag:WHpCneDFBCljS7ICSReOfg==,type:str]
    TELEGRAM_ID: ENC[AES256_GCM,data:ZTmUH+htgl7m,iv:VouYVXs5aFVZ33QsbLH7UGNFl9C57co92JUOhYKetjs=,tag:fgap8hVgERGj4PqdrI6lxg==,type:str]
    TELEGRAM_API: ENC[AES256_GCM,data:fj5ODDmoHPrRbnqScwBv7hUsn+L5P8Zoz2sthr4Cn8/qPFVAiZTGORQnOwQpUQ==,iv:HiQy5mNvexxTLLFpz8aPHqKQEaVJtXOL68pqORLBVeY=,tag:da/pWCaSDlsCz3Q0Bn1dFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10evyvm8h8ez8wwftltzy6ccg4kk3q3r5rfgkv3e7d83l298a5ufsgmv6er
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbFk0T2xGQVBvQWNLcmNO
            NG1HRkkvaWVNTXBLT3lmSkE3QXFtRERCa1NZClI1S1FtelRlbVg0QXhJeWMvbWYy
            Q05LWXQ1NU5FS3FjOEZCRnNRT1ptdGsKLS0tIG5iWThDN1o3bkE2dUlwTjdGQlN0
            QzRLcXZkWHArVEYyRmJGSGs4RHI2QjQKyrCT70H5F44GenjpchNLp9dye2SN2ek2
            Guat5k3F951lkx8eai/hDPMVSRuY2E3OCz4GIK1kkKnMVlUJykGQQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T11:34:30Z"
    mac: ENC[AES256_GCM,data:JP+B9Rj9o1txgFeVS7oTAea6Yqy66xn8yyEaoKFI4EBwzadc43rPFetT95TgMy3kiL5D8sH55MHtEgaSnzpMYuNF+YgjDjE6NYcFeMM4BEeKBo4zxdPyC7a9XHRfPmhZ4VumzLQbTzeQDdZz2e5GmI2OjGKpDQzpm/A5wnb5gVc=,iv:alaTAa5kF6HwjyzP2C1ZUzFp32p8/i6I4agkJWbyCos=,tag:jKC6Spd9EiY8RaxZU7Ym6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
