apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: default
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:HPbmfTXOI2/O+6bmBhg2e2xF2Je6/q0b4q1u9W+tHOQ=,iv:PKiJB3PxVQoypgTThMWW3TQzP8euq/CCxZdC0MxHTJs=,tag:6m8f8cZ9Y4Zi44n3zyUJLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10evyvm8h8ez8wwftltzy6ccg4kk3q3r5rfgkv3e7d83l298a5ufsgmv6er
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcUo5d1F5UzZEV1Niak1i
            Mk5EeTFWQW00aVdxd3Q3NS9LUlA0TGZFdG1VCi92VHZQcWJFNDMyY0Z0L3RuRmo2
            UzJNazZZaEVFa1ltSXZ2Ky9GSC8vUDgKLS0tIDE2Vy9VcmVac1QzNGdabktXZStN
            aGcyallDbkhoOFNvVW50VXpWWVVDVDAKGja6rbYpFvC9x9nGJECXXXhDd/9CBTGx
            6r5kez2NtrUsIVGPD3AItdxb+KJo0QgNqbFhqMwSdeRwIdhKfLIYkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-08T19:51:11Z"
    mac: ENC[AES256_GCM,data:ugr2q+YcO31tKN6TPxOAfrELAs/O/VslR+PrJJzRHmi0THRd56Krx5fUkRO1r+i6Nr8z8SsaYtLi3N+XNEUBk7TmxwhOvOJf70vYehrhYnAF/LlOgZ0hFk6xIrPZkyEnCDUgUCYV8Vnt8zl4D4YLcMzwiaV49AkE92tU1Q2a9Jg=,iv:ec0Ym/kNEwtUZSiaybLS3yVgf5YLpXEUm3kzoVActIY=,tag:sWcOVmYw7KtSD2Jy53SpHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
