apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: default
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:b35Y8hE1qWp2is+4MVAdxj5wfVl22tbNNWwGTrAbuwM=,iv:EJ88IP9rKrHMQkix/MCnVPzIS+AwB8xtqkbvrjxYoKA=,tag:eKAhldqBrKQ+2OmL+kLksQ==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:f3HxYgQDrQJRd448PBaXRI/HVyqm+CIEOTqQQVX7gfU=,iv:GBrCOidKSOxxEKF0qzorv1uA0ZhGxf8gtqCz66lcOCE=,tag:LMEGUXLEDurY2oHfX66Qaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10evyvm8h8ez8wwftltzy6ccg4kk3q3r5rfgkv3e7d83l298a5ufsgmv6er
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYStSTUlkb1pBSFg1VGRG
            aktGVGJ5SDMzN2NGNXNSWXllMk9wWHNUTmdBCk04MURVUHZyN0pQL0J3ZmluaGxx
            T2h3YXc1dTRudVgzOGRobGNqNW9kNUUKLS0tIGJ6WCtnZC9WOWR0QmhvVWdGcENO
            SU1QbGdxd0pIQ011T2ZnbkwyTDg0MXcKagFU/iYQQhcdorc9QfVlWgfoXeNLdEuD
            2K4ydGpw/70HLrAybEKbxG5nhultKnXNRz86/pWAMbMfD5oblybDJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-08T20:14:34Z"
    mac: ENC[AES256_GCM,data:CRWYtcEBMOmDDVmbzGZZy5gwWO3dRnvhWXBU9MYcegNchpPgwqYQ6ECIQNqyPI7qW1seM7vAfMvCugmpaitFFYsOlM8aKYY6sSNHJCXCwSQnwJx7SxINjbuB+5/VQgqNkIwwgV3LKbsqEgSfck8Oa4yjeXOHbNsEun7nDxlFW+E=,iv:psYQ3q/j2uSC6v7WOIt7Xhmcd+GYCckx263P5V8I4vE=,tag:zYj2dmVD5xEz3dMDShWQog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
